// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-RGS3liwt_XljWcpP2DxVoqz3XWJcYlE',
    appId: '1:105431920883:web:94c65f327a21e802eac786',
    messagingSenderId: '105431920883',
    projectId: 'wimpillay-rtu',
    authDomain: 'wimpillay-rtu.firebaseapp.com',
    storageBucket: 'wimpillay-rtu.firebasestorage.app',
    measurementId: 'G-1KMSH8SBW9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdd3IgIFEReGlteAy9-XVWkwzyYTT-5v4',
    appId: '1:105431920883:android:629b1fbf689e8390eac786',
    messagingSenderId: '105431920883',
    projectId: 'wimpillay-rtu',
    storageBucket: 'wimpillay-rtu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9uUvUZPfl7omnw6XFTBh8RJjEUJnZ5NA',
    appId: '1:105431920883:ios:8b74a41a6f0fbeeceac786',
    messagingSenderId: '105431920883',
    projectId: 'wimpillay-rtu',
    storageBucket: 'wimpillay-rtu.firebasestorage.app',
    iosBundleId: 'com.example.wimpillay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9uUvUZPfl7omnw6XFTBh8RJjEUJnZ5NA',
    appId: '1:105431920883:ios:8b74a41a6f0fbeeceac786',
    messagingSenderId: '105431920883',
    projectId: 'wimpillay-rtu',
    storageBucket: 'wimpillay-rtu.firebasestorage.app',
    iosBundleId: 'com.example.wimpillay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-RGS3liwt_XljWcpP2DxVoqz3XWJcYlE',
    appId: '1:105431920883:web:33c6c1c3c36fdd33eac786',
    messagingSenderId: '105431920883',
    projectId: 'wimpillay-rtu',
    authDomain: 'wimpillay-rtu.firebaseapp.com',
    storageBucket: 'wimpillay-rtu.firebasestorage.app',
    measurementId: 'G-GR1SMPJ8WX',
  );
}
